### ISSUE TITLE
is possible to add consumption from Grid

### ISSUE THREAD

**Issue by go2thanawat** [dmslabsbr/hoymiles#111]
i see hoymile cloud is has "electric consumption from grid data"  
is possible to add consumption from Grid to this add-on

**Comment by Cosik** [comment]
Yes, it is possible, but I have no access to such installation.

**Comment by mmz06** [comment]
Hi @Cosik 
Shall I provide you with a user account on my plant so you can access this maybe ?
I'm not really familiar with this, how can I provide you the credentials, as I can't find any way to send it to you as personal ?

**Comment by Cosik** [comment]
@mmz06 yes, probably I will need access to your plant. When I will have some spare time I will back to you.

**Comment by Wind06** [comment]
Hi @Cosik did you get  access to such configuration to get Grid data ?
If not I can give you access to my plant, I am interested by getting such information.
Thanks,

**Comment by Wind06** [comment]
Hi @Cosik, yes I know but if I give you access to my plant would it be possible for you to get such data with the Addon ?

**Comment by Cosik** [comment]
Should be, I need to check responses of requests and adapt code if possible.

**Comment by Wind06** [comment]
Can I send you the access on a private mailbox 😉

**Comment by Cosik** [comment]
Yes, please.

**Comment by Wind06** [comment]
hmm not very familiar with GitHub, but cannot find your email address. How can I proceed?

**Comment by Cosik** [comment]
@Wind06 maybe reach me over discord.

**Comment by Wind06** [comment]
Hi Cosik, I think that you send me an invite under discord but I lost it, can you please resend it. Thanks and sorry for that.

**Comment by ebiancarelli** [comment]
My system returns this block of data
`{
  "today_eq": "0.17",
  "month_eq": "131.1",
  "year_eq": "1805.07",
  "total_eq": "1805.07",
  "real_power": "277.1",
  "co2_emission_reduction": "1.79966",
  "plant_tree": "98",
  "data_time": "2023-10-27 08:15:58",
  "last_data_time": "2023-10-27T08:15:58-06:00",
  "capacitor": "2000.0",
  "is_balance": 0,
  "is_reflux": 1,
  "reflux_station_data": {
    "start_date": "",
    "end_date": "",
    "pv_power": "277.1",
    "grid_power": "-180",
    "load_power": "457.1",
    "bms_power": "0",
    "bms_soc": "0",
    "inv_num": 0,
    "meter_location": 2,
    "pv_to_load_eq": "0",
    "load_from_pv_eq": "0",
    "meter_b_in_eq": "5317230.832999999",
    "meter_b_out_eq": "0",
    "bms_in_eq": "0",
    "bms_out_eq": "0",
    "self_eq": "1805071",
    "pv_eq_total": "0",
    "use_eq_total": "0",
    "flows": [
      {
        "out": 2,
        "in": 1
      },
      {
        "out": 4,
        "in": 1
      }
    ],
    "icon_pv": 0,
    "icon_grid": 1,
    "icon_load": 1,
    "icon_bms": 1,
    "icon_gen": 0,
    "icon_pvi": 0,
    "mb_in_eq": {
      "today_eq": "0",
      "month_eq": "0",
      "year_eq": "0",
      "total_eq": "0"
    },
    "mb_out_eq": {
      "today_eq": "0",
      "month_eq": "0",
      "year_eq": "0",
      "total_eq": "0"
    }
  },
  "real_power_measurement": "277.1",
  "real_power_total_increasing": "277.1",
  "power_ratio": "13.9",
  "capacitor_kW": "2.0",
  "today_eq_Wh": "167.0"
}`

The grid info is contained in an enclosed json struct here with `grid_power` and `load_power` being interesting data points to graph.
`"reflux_station_data": {
    "start_date": "",
    "end_date": "",
    "pv_power": "277.1",
    "grid_power": "-180",
    "load_power": "457.1",
    "bms_power": "0",
    "bms_soc": "0",
    "inv_num": 0,
    "meter_location": 2,
    "pv_to_load_eq": "0",
    "load_from_pv_eq": "0",
    "meter_b_in_eq": "5317230.832999999",
    "meter_b_out_eq": "0",
    "bms_in_eq": "0",
    "bms_out_eq": "0",
    "self_eq": "1805071",
    "pv_eq_total": "0",
    "use_eq_total": "0",
    "flows": [
      {
        "out": 2,
        "in": 1
      },
      {
        "out": 4,
        "in": 1
      }
    ],
    "icon_pv": 0,
    "icon_grid": 1,
    "icon_load": 1,
    "icon_bms": 1,
    "icon_gen": 0,
    "icon_pvi": 0,
    "mb_in_eq": {
      "today_eq": "0",
      "month_eq": "0",
      "year_eq": "0",
      "total_eq": "0"
    },
    "mb_out_eq": {
      "today_eq": "0",
      "month_eq": "0",
      "year_eq": "0",
      "total_eq": "0"
    }
  },`

**Comment by Cosik** [comment]
@ebiancarelli but I need requests also to know how to implement it.

**Comment by ebiancarelli** [comment]
The block of JSON shown is gotten from MQTT using the 'stable' branch of code. If I guess, I think the json to dictionary is only taking the top level of tags, and not recursing into tags with additional elements.

**Comment by Cosik** [comment]
But need more info, current implementation based on `pvm/station_select_device_of_tree` which defined how installation looks like. On this list has to be meter also. Then I could add it as other stuff.

**Comment by ebiancarelli** [comment]
I sent you a friend request on Discord.

**Comment by ebiancarelli** [comment]
Does this help?

```
2023-10-27 12:14:28,888 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm/station_select_device_of_tree

2023-10-27 12:14:28,890 - HoymilesAdd-on.hoymilesapi.Hoymiles - DEBUG - {'Content-Type': 'application/json;charset=UTF-8', 'Cache-Control': 'no-cache', 'Host': 'global.hoymiles.com', 'Connection': 'keep-alive', 'Accept': 'application/json, text/plain, */*', 'Accept-Encoding': 'gzip, deflate, br', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36', 'Accept-Language': 'pt-BR,pt;q=0.9,it-IT;q=0.8,it;q=0.7,es-ES;q=0.6,es;q=0.5,en-US;q=0.4,en;q=0.3', 'Cookie': "'uid=fff9c382-389f-4a47-8dc9-c5486fc3d9f5; hm_token=1.wPHrxCR7XZ8DK7p2Lx7asgCp200MhDHPv9iBs2irrgL69YYUMj9url4yZ47MDvw9vwSuntubZ4JZi5CK3IkjVf; Path=/; Domain=.global.hoymiles.com;Expires=Sat, 30 Mar 2024 22:11:48 GMT;'", 'Content-Length': '69'}

2023-10-27 12:14:30,313 - HoymilesAdd-on.hoymilesapi.Hoymiles - DEBUG - content: b'{"status":"0","message":"success","data":[{"id":980570,"sn":"10FD81844117","vc":"","dtu_sn":"10FD81844117","type":1,"version":3,"replace_num":0,"model_no":"DTU-Pro-S","soft_ver":"V00.02.14","hard_ver":"H09.06.01","extend_data":{},"warn_data":{"_rw":"","connect":true,"warn":false},"children":[{"id":4457570,"sn":"116481038963","vc":"","dtu_sn":"10FD81844117","type":3,"version":3,"replace_num":0,"model_no":"HMS-1800-4T","soft_ver":"V01.00.14","hard_ver":"H00.04.00","extend_data":{"grid_name":"","port_array":[1,2,3,4],"grid_id":0,"grid_version":""},"warn_data":{"warn":false,"connect":true},"children":[]}]}],"systemNotice":null}'
```

**Comment by Wind06** [comment]
> I sent you a friend request on Discord.

Hmm are you sure I did not get any request .... check wind0613 instead of wind06

**Comment by ebiancarelli** [comment]
> > I sent you a friend request on Discord.
> 
> Hmm are you sure I did not get any request .... check wind0613 instead of wind06

I sent the request to @Cosik .

**Comment by Wind06** [comment]
Ah ok :-)

**Comment by Cosik** [comment]
@ebiancarelli no sorry it not help, I didn't see meter on this request. About discord, I realized that it changed user identyfication so I will be Cosik#6329

**Comment by Cosik** [comment]
@ebiancarelli and @Wind06 I'm looking in to code, and what is send and I realized that data could be added by manual configuration of mqtt entities.

**Comment by Cosik** [comment]
@ebiancarelli and @Wind06 please check #119 and test it.

**Comment by Wind06** [comment]
@Cosik Many thanks for your help and quick update. I will test it tomorrow and give an update

**Comment by Wind06** [comment]
Hello, all data seems to be reported correctly. 
A big THANKS to @Cosik for his quick help and new version of the Addon.

**Comment by ebiancarelli** [comment]
How do I test? Do I need to run the 'edge' version of the addon?

**Comment by Cosik** [comment]
it is on edge version

**Comment by ebiancarelli** [comment]
I'm not seeing anything different after waiting for the sensor data to be updates (I can see MQTT messages). I can't seem to get the `edge` version to show me DEBUG logs either so I can't troubleshoot

**Comment by Wind06** [comment]
Maybe need to reload the Sensors view, or delete it and recreate it.
check also the version of the Addon it must be 

HoyMiles Solar Gateway Edge Addon 
Current version: 1.2.1

**Comment by Cosik** [comment]
@ebiancarelli did you check configuration?

**Comment by ebiancarelli** [comment]
My addon version is 1.1.1 (edge)...

**Comment by Wind06** [comment]
you need to update it :-)

**Comment by ebiancarelli** [comment]
Yes... How do I force that to happen?

@Cosik , I have 
```
DEVELOPERS_MODE: true
LOG_LEVEL: DEBUG
```

**Comment by Wind06** [comment]
When selecting the Addon on top of your screen you should be prompted for new version update. You can try selecting the "Additional modules shop" and select top right "Check for updates"

**Comment by ebiancarelli** [comment]
don't see it when I run `ha addons info 44349f66_hoymiles_solardata_edge`
```
version: 1.1.1
version_latest: 1.1.1
```

**Comment by Cosik** [comment]
Because you still using stable version...

**Comment by ebiancarelli** [comment]
Let me make sure I'm adding the addon properly. This is what I see in the AddOn Store after adding the repo.

<img width="782" alt="image" src="https://github.com/dmslabsbr/hoymiles/assets/156859/db6731f1-e699-4021-8ea7-8a4865a7c102">

Then I select the 'Edge' version.

Is that correct?

**Comment by Wind06** [comment]
Yes that's correct and you should see version  1.2.1

**Comment by ebiancarelli** [comment]
Here are infos from the command line. and a selected snip -
```
update_available: false
url: https://github.com/dmslabsbr/hoymiles/tree/master/edge
usb: false
version: 1.1.1
version_latest: 1.1.1
```
---------------------------------------

➜  ~ ha addons upgrade  44349f66_hoymiles_solardata_edge   
Processing... Done.

Error: No update available for add-on 44349f66_hoymiles_solardata_edge
➜  ~ ha addons info  44349f66_hoymiles_solardata_edge 
advanced: false
apparmor: default
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
audio: false
audio_input: null
audio_output: null
auth_api: false
auto_update: false
available: true
boot: auto
build: true
changelog: true
description: Read Hoymiles Gateway Solar Data Edge Version.
detached: false
devices: []
devicetree: false
discovery: []
dns:
- 44349f66-hoymiles-solardata-edge.local.hass.io
docker_api: false
documentation: true
full_access: false
gpio: false
hassio_api: false
hassio_role: default
homeassistant: null
homeassistant_api: false
host_dbus: false
host_ipc: false
host_network: true
host_pid: false
host_uts: false
hostname: 44349f66-hoymiles-solardata-edge
icon: true
ingress: true
ingress_entry: /api/hassio_ingress/nllDTecfXQ7HB4WooneV0iirxl9vGC5f9cCUrI9SKEk
ingress_panel: false
ingress_port: 5000
ingress_url: /api/hassio_ingress/nllDTecfXQ7HB4WooneV0iirxl9vGC5f9cCUrI9SKEk/
ip_address: 172.30.32.1
kernel_modules: false
logo: true
long_description: "# HoyMiles Solar Data Gateway Add-on Edge version\nDevelopment
  versions can be unstable.\n\nApplication to read Hoymiles Gateway Solar Data using
  unofficial API\n\nI developed this program to integrate my solar system data to
  [Home Assistant](https://www.home-assistant.io/) Application through an add-on.\n\nNow,
  [Cosik](https://github.com/Cosik)  is helping too.\n\n[![Open your Home Assistant
  instance and show the add add-on repository dialog with a specific repository URL
  pre-filled.](https://my.home-assistant.io/badges/supervisor_add_addon_repository.svg)](https://my.home-assistant.io/redirect/supervisor_add_addon_repository/?repository_url=https%3A%2F%2Fgithub.com%2Fdmslabsbr%2Fhoymiles)\n\nBut
  you can use the application without using the Home Assistant. You just need a machine
  that runs Python3. It based on mqtt messages, so could be send from any device to
  MQTT Broker.\n\n<a href=\"https://www.buymeacoffee.com/dmslabs\"><img src=\"https://img.buymeacoffee.com/button-api/?text=Buy
  me a pizza&emoji=\U0001F355&slug=dmslabs&button_colour=FFDD00&font_colour=000000&font_family=Cookie&outline_colour=000000&coffee_colour=ffffff\"></a>\n\n[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=9S3JYKPHR3XQ6)\n[![Donate
  with Bitcoin](https://en.cryptobadges.io/badge/micro/1MAC9RBnPYT9ua1zsgvhwfRoASTBKr4QL8)](https://www.blockchain.com/btc/address/1MAC9RBnPYT9ua1zsgvhwfRoASTBKr4QL8)\n\nDonate
  Cosik -> \n[![Donate Cosik](https://img.shields.io/badge/Donate-PayPal-green.svg)](paypal.me/cosik3d)\n\n<img
  alt=\"Lines of code\" src=\"https://img.shields.io/tokei/lines/github/dmslabsbr/hoymiles\">\n<img
  alt=\"GitHub last commit\" src=\"https://img.shields.io/github/last-commit/dmslabsbr/hoymiles\">\n\n\n#
  Instructions\n\n<img align=\"center\" src=\"https://github.com/dmslabsbr/smsUps/raw/master/hass.io.png\"
  alt=\"\" width=\"30\" /> [Home Assistant add-on instructions](DOCS.md)\n\n\nBefore
  run you need to install:\n   https://github.com/eclipse/paho.mqtt.python  ***and***\n
  \  https://github.com/psf/requests\n\n\n```bash\ngit clone https://github.com/dmslabsbr/hoymiles.git\ncd
  hoymiles\npython3 -m venv ./hoymiles/\nsource ./bin/activate\npip3 install paho-mqtt\npip3
  install requests\npip3 install python-dateutil\n```\n\nMy solar panels communicate
  with the internet using a DTU-W100 gateway.\n\n<img src=\"https://github.com/dmslabsbr/hoymiles/raw/master/img/icon.png\"
  alt=\"\" width=\"300\" />\n\nBut it will probably work with any device that uses
  the [global.hoymiles.com](https://global.hoymiles.com/) Website. It was tested with
  DTU-PRO also.\n\n\n## PS:\nI invite everyone to help in the this tool development.\n\n##
  Screenshots\n\n<img src=\"https://github.com/dmslabsbr/hoymiles/blob/master/edge/img/Hass1.png?raw=true\"
  alt=\"\" width=\"400\" />\n\n<img src=\"https://github.com/dmslabsbr/hoymiles/blob/master/edge/img/Hass2.png?raw=true\"
  alt=\"\" width=\"400\" />\n\n<img src=\"https://github.com/dmslabsbr/hoymiles/blob/master/edge/img/Hass3.png?raw=true\"
  alt=\"\" width=\"400\" />\n\n\n\n#### Licence\n\n> THE SOFTWARE IS PROVIDED \"AS
  IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
  TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
  OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.\n"
machine: []
name: HoyMiles Solar Gateway Edge Addon
network: null
network_description: null
options:
  DEVELOPERS_MODE: false
  External_MQTT_Server: false
  FILE_PATH: hoymiles.log
  HOYMILES_PASSWORD: HOYMILES_PASSWORD
  HOYMILES_PLANT_ID: "123"
  HOYMILES_USER: HOYMILES_USER
  LOG_LEVEL: INFO
  LOG_TO_FILE: false
  MQTT_Host: Internal - Change here if you use another server
  MQTT_Pass: Automatically obtained from Home Assistant - Change here if you use another
    server
  MQTT_TLS: false
  MQTT_TLS_PORT: "8883"
  MQTT_User: Automatically obtained from Home Assistant - Change here if you use another
    server
privileged: []
protected: true
rating: 6
repository: 44349f66
schema:
- name: HOYMILES_USER
  required: true
  type: string
- format: password
  name: HOYMILES_PASSWORD
  required: true
  type: string
- name: HOYMILES_PLANT_ID
  required: true
  type: string
- name: External_MQTT_Server
  required: true
  type: boolean
- name: MQTT_Host
  optional: true
  type: string
- name: MQTT_User
  optional: true
  type: string
- format: password
  name: MQTT_Pass
  optional: true
  type: string
- name: MQTT_TLS
  required: true
  type: boolean
- name: MQTT_TLS_PORT
  required: true
  type: integer
- name: DEVELOPERS_MODE
  required: true
  type: boolean
- name: LOG_LEVEL
  optional: true
  options:
  - DEBUG
  - INFO
  - WARNING
  - ERROR
  - CRITICAL
  type: select
- name: LOG_TO_FILE
  required: true
  type: boolean
- name: FILE_PATH
  optional: true
  type: string
services:
- mqtt:need
signed: false
slug: 44349f66_hoymiles_solardata_edge
stage: stable
startup: application
state: unknown
stdin: false
translations:
  en:
    configuration:
      DEVELOPERS_MODE:
        description: Set logging level to DEBUG.
        name: Developer's Mode
      External_MQTT_Server:
        description: 'Select to use an external MQTT Server.  '
        name: External_MQTT_Server
      FILE_PATH:
        description: File name to use for logging to file.
        name: FILE_PATH
      HOYMILES_PASSWORD:
        description: S-Miles Cloud login password.
        name: HOYMILES_PASSWORD
      HOYMILES_PLANT_ID:
        description: S-Miles Cloud plant ID.  Multiple plants allowed, separated by
          ','
        name: HOYMILES_PLANT_ID
      HOYMILES_USER:
        description: S-Miles Cloud login username.
        name: HOYMILES_USER
      LOG_LEVEL:
        description: Must be one of DEBUG, INFO, WARNING, ERROR, or CRITICAL
        name: LOG_LEVEL
      LOG_TO_FILE:
        description: Enable logging to file.
        name: LOG_TO_FILE
      MQTT_Host:
        description: Required if using an external MQTT Server.
        name: MQTT_Host
      MQTT_Pass:
        description: Required if using an external MQTT Server.
        name: MQTT_Pass
      MQTT_User:
        description: Required if using an external MQTT Server.
        name: MQTT_User
uart: false
udev: false
**update_available: false
url: https://github.com/dmslabsbr/hoymiles/tree/master/edge
usb: false
version: 1.1.1
version_latest: 1.1.1**
video: false
watchdog: false
webui: null

**Comment by Cosik** [comment]
@ebiancarelli please check again. I've found error in configuration files.

**Comment by ebiancarelli** [comment]
I removed the repo and added it back.

I see that the stable addon is v1.0.8. Edge is v1.1.1.

Does HA cache addon info that I need to purge?

<img width="1041" alt="image" src="https://github.com/dmslabsbr/hoymiles/assets/156859/8c906018-1e16-4d03-94e5-8b591eed8acd">

**Comment by Cosik** [comment]
@ebiancarelli sorry there were much more things to fix. I wonder why I didn't noticed that oldStable disappear. Now by removing and adding repo again, you should see 1.2.1 in edge and oldStable version.
![image](https://github.com/dmslabsbr/hoymiles/assets/1255379/b6fdcdce-863d-4d03-ba62-6e5d6f9c57c8)

**Comment by ebiancarelli** [comment]
That did it for me. I was able to install v1.2.1 and see the new meter sensors.

Thanks!!!

**Comment by mmz06** [comment]
Works perfectly from my side as well. 
Thank you @Cosik :-)
